name = "xybuddy-stats"
main = "src/index.ts"
compatibility_date = "2024-11-11"
workers_dev = false

routes = [
  { pattern = "api.xybuddy.xyz", custom_domain = true }
]

[[kv_namespaces]]
binding = "XYBUDDY_STATS"
id = "1ae725ec512044eda32621a83b13ce5f"
